modLoader="javafml"
loaderVersion="[${loader_version},)"
license="All rights reserved"
issueTrackerURL="https://github.com/MeinKraft/Crimson-Coals/issues" #optional

[[mods]]
modId="crimsoncoals"
version="${version}"
displayName="Crimson Coals"
displayURL="https://www.curseforge.com/minecraft/mc-mods/crimson-coals"
authors="§4Crimson_Fluff"
logoFile="logo.png" #optional
credits="\n§bRaziel23x§r for casually giving me the push I needed !\n§bTechnovision§r for his awesome modding YouTube series\n§bTurtyWurty§r for his awesome modding YouTube series" #optional
description=''' "From acorns mighty oaks... get cut down for firewood" '''

[[dependencies.crimsoncoals]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mc_version}]"
    side="BOTH"
[[dependencies.crimsoncoals]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    side="BOTH"
